apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-go-app
  template:
    metadata:
      labels:
        app: my-go-app
    spec:
      imagePullSecrets:
        - name: my-registry-secret
      containers:
        - name: my-go-app
          image: crpi-13j8dbuyvy0s82p4.cn-hangzhou.personal.cr.aliyuncs.com/zjj_go_repo/go_repo:latest # 替换为你的镜像