name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64
          go build -v ./...


      - name: Test
        run: go test -v ./...

      - name: Log in to Docker Registry
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login crpi-13j8dbuyvy0s82p4.cn-hangzhou.personal.cr.aliyuncs.com -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t crpi-13j8dbuyvy0s82p4.cn-hangzhou.personal.cr.aliyuncs.com/zjj_go_repo/go_repo:latest .
          docker run --rm crpi-13j8dbuyvy0s82p4.cn-hangzhou.personal.cr.aliyuncs.com/zjj_go_repo/go_repo:latest ls /

      - name: Push Docker Image
        run: |
          docker push crpi-13j8dbuyvy0s82p4.cn-hangzhou.personal.cr.aliyuncs.com/zjj_go_repo/go_repo:latest
